import AppKit
import Foundation
import Observation

@MainActor
@Observable
final class ClipboardManager {
    static let shared = ClipboardManager()

    private(set) var items: [ClipboardItem] = []
    var ignoredApps: [IgnoredApp] {
        didSet { persistIgnoredApps() }
    }

    private let store = ClipboardStore.shared
    private var pollTimer: Timer?
    private var saveTimer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    /// Pinned items first (newest pin first), then unpinned newest-first.
    var displayItems: [ClipboardItem] {
        let pinned = items.filter(\.isPinned)
        let unpinned = items.filter { !$0.isPinned }
        return pinned + unpinned
    }

    private init() {
        if let data = UserDefaults.standard.data(forKey: "ignoredApps"),
           let apps = try? JSONDecoder().decode([IgnoredApp].self, from: data) {
            ignoredApps = apps
        } else {
            ignoredApps = []
        }
        items = store.load()
    }

    // MARK: - Polling

    func startPolling() {
        guard pollTimer == nil else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.checkPasteboard() }
        }
        RunLoop.main.add(timer, forMode: .common)
        pollTimer = timer
    }

    func stopPolling() {
        pollTimer?.invalidate()
        pollTimer = nil
    }

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        // Respect password managers and other apps marking content as transient/concealed.
        let skipMarkers = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        if skipMarkers.contains(where: { types.contains(NSPasteboard.PasteboardType($0)) }) { return }

        let frontmost = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontmost?.bundleIdentifier,
           ignoredApps.contains(where: { $0.bundleID == bundleID }) {
            return
        }

        if types.contains(.png) || types.contains(.tiff) {
            captureImage(from: pasteboard, source: frontmost)
        } else if let text = pasteboard.string(forType: .string),
                  !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            captureText(text, source: frontmost)
        }
    }

    private func captureText(_ text: String, source: NSRunningApplication?) {
        // Dedupe: identical text moves to the top instead of duplicating.
        if let index = items.firstIndex(where: { $0.kind == .text && $0.text == text }) {
            var existing = items.remove(at: index)
            existing.date = Date()
            items.insert(existing, at: 0)
            scheduleSave()
            return
        }

        let item = ClipboardItem(
            id: UUID(),
            kind: .text,
            text: text,
            imageFilename: nil,
            byteSize: text.utf8.count,
            pixelWidth: nil,
            pixelHeight: nil,
            sourceBundleID: source?.bundleIdentifier,
            sourceAppName: source?.localizedName,
            sourceAppPath: source?.bundleURL?.path,
            date: Date(),
            isPinned: false
        )
        items.insert(item, at: 0)
        enforceHistoryCap()
        scheduleSave()
    }

    private func captureImage(from pasteboard: NSPasteboard, source: NSRunningApplication?) {
        var pngData: Data?
        var width: Int?
        var height: Int?

        if let data = pasteboard.data(forType: .png) {
            pngData = data
        } else if let tiff = pasteboard.data(forType: .tiff),
                  let rep = NSBitmapImageRep(data: tiff) {
            pngData = rep.representation(using: .png, properties: [:])
        }
        guard let pngData else { return }

        if let rep = NSBitmapImageRep(data: pngData) {
            width = rep.pixelsWide
            height = rep.pixelsHigh
        }

        guard let filename = store.writeImage(pngData) else { return }

        let item = ClipboardItem(
            id: UUID(),
            kind: .image,
            text: nil,
            imageFilename: filename,
            byteSize: pngData.count,
            pixelWidth: width,
            pixelHeight: height,
            sourceBundleID: source?.bundleIdentifier,
            sourceAppName: source?.localizedName,
            sourceAppPath: source?.bundleURL?.path,
            date: Date(),
            isPinned: false
        )
        items.insert(item, at: 0)
        enforceImageLimit()
        enforceHistoryCap()
        scheduleSave()

        // OCR + QR detection off the main thread; results attached when done.
        let itemID = item.id
        Task { [weak self] in
            let result = await ImageAnalysisService.analyze(pngData)
            guard let self, result.text != nil || result.qrPayload != nil else { return }
            if let index = self.items.firstIndex(where: { $0.id == itemID }) {
                self.items[index].ocrText = result.text
                self.items[index].qrPayload = result.qrPayload
                self.scheduleSave()
            }
        }
    }

    /// Keep at most `AppState.maxImages` unpinned images; evict the oldest ones.
    private func enforceImageLimit() {
        let limit = AppState.shared.maxImages
        let unpinnedImages = items.filter { $0.kind == .image && !$0.isPinned }
        guard unpinnedImages.count > limit else { return }
        let toRemove = unpinnedImages.sorted { $0.date < $1.date }.prefix(unpinnedImages.count - limit)
        let removeIDs = Set(toRemove.map(\.id))
        store.deleteImageFiles(for: Array(toRemove))
        items.removeAll { removeIDs.contains($0.id) }
    }

    /// Optional overall cap on unpinned items (0 = unlimited).
    private func enforceHistoryCap() {
        let cap = AppState.shared.historyCap
        guard cap > 0 else { return }
        let unpinned = items.filter { !$0.isPinned }
        guard unpinned.count > cap else { return }
        let toRemove = unpinned.sorted { $0.date < $1.date }.prefix(unpinned.count - cap)
        let removeIDs = Set(toRemove.map(\.id))
        store.deleteImageFiles(for: toRemove.filter { $0.kind == .image })
        items.removeAll { removeIDs.contains($0.id) }
    }

    // MARK: - Mutations

    func delete(_ item: ClipboardItem) {
        if item.kind == .image { store.deleteImageFiles(for: [item]) }
        items.removeAll { $0.id == item.id }
        scheduleSave()
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        scheduleSave()
    }

    func clearHistory() {
        let dropped = items.filter { !$0.isPinned }
        store.deleteImageFiles(for: dropped)
        items = items.filter(\.isPinned)
        saveNow()
    }

    func addIgnoredApp(bundleID: String, name: String, path: String) {
        guard !ignoredApps.contains(where: { $0.bundleID == bundleID }) else { return }
        ignoredApps.append(IgnoredApp(bundleID: bundleID, name: name, path: path))
    }

    func removeIgnoredApp(_ app: IgnoredApp) {
        ignoredApps.removeAll { $0.bundleID == app.bundleID }
    }

    // MARK: - Persistence

    private func scheduleSave() {
        saveTimer?.invalidate()
        saveTimer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { [weak self] _ in
            Task { @MainActor in self?.saveNow() }
        }
    }

    func saveNow() {
        saveTimer?.invalidate()
        saveTimer = nil
        store.save(items)
    }

    private func persistIgnoredApps() {
        if let data = try? JSONEncoder().encode(ignoredApps) {
            UserDefaults.standard.set(data, forKey: "ignoredApps")
        }
    }
}
